/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_Rule_RuleImpl */

#ifndef _Included_com_example_demo_Rule_RuleImpl
#define _Included_com_example_demo_Rule_RuleImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_Rule_RuleImpl
 * Method:    verify
 * Signature: (Lcom/example/demo/plan/Plan;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_demo_Rule_00024RuleImpl_verify
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
