/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_plan_Plan */

#ifndef _Included_com_example_demo_plan_Plan
#define _Included_com_example_demo_plan_Plan
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
