/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_Rule */

#ifndef _Included_com_example_demo_Rule
#define _Included_com_example_demo_Rule
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
