/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_Rule_RuleImpl_1 */

#ifndef _Included_com_example_demo_Rule_RuleImpl_1
#define _Included_com_example_demo_Rule_RuleImpl_1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_Rule_RuleImpl_1
 * Method:    verify
 * Signature: (Ljava/util/Map;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_demo_Rule_00024RuleImpl_11_verify
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
