/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_Rule_RuleInterface */

#ifndef _Included_com_example_demo_Rule_RuleInterface
#define _Included_com_example_demo_Rule_RuleInterface
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
